# Site settings
title: Сергей Куликов
email: serguey.kulikov@gmail.com
description: >
  Junior front-end developer living in Dnipropetrovsk, Ukraine.
baseurl: ""
url: "http://web-padawan.github.io"
twitter_username: kulikov_dp
github_username:  web-padawan

# Build settings
markdown: kramdown
